### ISSUE TITLE
Shouldn't echo have '-n'?

### ISSUE THREAD

**Issue by 3lpsy** [frizb/OSCP-Survival-Guide#4]
Shouldn't  ```echo "QWxhZGRpbjpvcGVuIHNlc2FtZQ==" | base64 --decode``` be ```echo -n "QWxhZGRpbjpvcGVuIHNlc2FtZQ==" | base64 --decode``` in order to not include the new line character? 

For hashing this would be problem; however, I'm not sure if it would affect base64.

**Comment by frizb** [comment]
Sounds like a good idea to me.  I played around with the -n parameter a bit.  Thanks for the KNOWLEDGE! Made the update to the guide.
